#####
# This is all that remains of Configuration.yaml file.
# By using packages: I'm pulling all other configuration files from individual golders, starting with Integrations
#####


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

readme:
