esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "wifissid"
  password: "wifipassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "accesspassword"

ota:
  password: "accesspassword"
